language: php
php:
    - 5.5
    - 5.6
    - 7.0
before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
notifications:
    email:
        - rafael@nery.info
	- cristianocinotti@gmail.com
