language: php
php:
    - 5.5
    - 5.6
    - 7.0
before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
notifications:
    email:
        - rafael@nery.info
        - cristianocinotti@gmail.com
